version: '3'

services:
  backend:
    build: ./
    container_name: nestjs-poc
    environment:
      - PORT=3000
      - JWT_SECRET=hidden_secret
      - MONGO_URI=mongodb://mongo_db/NestDB

    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - nestjs_network 

  database:
    image: mongo
    container_name: mongo_db
    ports:
      - '27017':'27017'
    volumes:
      - ./mongodb-volumes:/data/db
    networks:
      - nestjs_network 

networks:
  nestjs_network:
    driver: bridge 